name: "terraform"

on: [push]

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: initialize
        run: terraform init
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan 



