name: shell commands

on: [push]

jobs:
  run-shell-commands:

    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: echo string
       run: echo "Jesus is Lord"

     - name: multi string
       run: |
         run: node -v
         run: npm -v